language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t imranq443/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true imranq443/react-test npm test

after_success:
  - docker build -t imranq443/multi-client -f ./client
  - docker build -t imranq443/multi-nginx -f ./nginx
  - docker build -t imranq443/multi-server -f ./server
  - docker build -t imranq443/multi-worker -f ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images
  - docker push imranq443/multi-client
  - docker push imranq443/multi-nginx
  - docker push imranq443/multi-server
  - docker push imranq443/multi-worker
