sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t imranq443/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true imranq443/react-test npm test

after_success:
  - docker build -t imranq443/multi-client ./client
  - docker build -t imranq443/multi-nginx ./nginx
  - docker build -t imranq443/multi-server ./server
  - docker build -t imranq443/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images
  - docker push imranq443/multi-client
  - docker push imranq443/multi-nginx
  - docker push imranq443/multi-server
  - docker push imranq443/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket-name: elasticbeanstalk-us-east-2-052929516571
  bucket-path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
# access_key_id: $AWS_ACCESS_KEY
# secret_access_key: $AWS_SECRET_KEY

# deploy:
#   edge: true
#   provider: elasticbeanstalk
